version: "3.0"
services:
  faas-gateway:
    build:
      context: ./faas-gateway
    ports:
      - "1337:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.40
      - CORS_ORIGIN=*
  rhymer:
    build:
      context: ./rhymer
    deploy:
      replicas: 1
    labels:
      - "faas.app=true"
      - "faas.name=rhymer"
      - "faas.port=8080"
  reducer:
    image: test 
    deploy:
      replicas: 1
    labels:
      - "faas.app=true"
      - "faas.name=reducer"
      - "faas.port=5000"
    environment:
      - CORS_ORIGIN="*"
