version: "3.0"
services:
  faas-gateway:
    image: eu.gcr.io/travtech/faas-gateway:latest
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.40
      - CORS_ORIGIN=http://trav.finsyn.se
  rhymer:
    image: eu.gcr.io/travtech/rhymer:latest
    labels:
      - "faas.app=true"
      - "faas.name=rhymer"
      - "faas.port=8080"
  reducer:
    image: eu.gcr.io/travtech/reducer:latest
    labels:
      - "faas.app=true"
      - "faas.name=reducer"
      - "faas.port=5000"
    environment:
      - CORS_ORIGIN="*"
